# Generated by Django 5.1.2 on 2024-11-19 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='exam name', max_length=20, verbose_name='exam name')),
                ('student_number', models.CharField(max_length=20, verbose_name='student number')),
                ('student_name', models.CharField(help_text='name', max_length=20, verbose_name='student name')),
                ('math_score', models.DecimalField(decimal_places=2, help_text='math scores', max_digits=5)),
                ('history_score', models.DecimalField(decimal_places=2, help_text='history scores', max_digits=5)),
                ('science_score', models.DecimalField(decimal_places=2, help_text='science_score', max_digits=5)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='grades.grade', verbose_name='class')),
            ],
            options={
                'verbose_name': 'score info',
                'verbose_name_plural': 'score info',
                'db_table': 'score',
            },
        ),
    ]
