# Generated by Django 5.1.2 on 2024-11-06 16:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(max_length=20, unique=True, verbose_name='student number')),
                ('student_name', models.CharField(max_length=50, verbose_name='student name')),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=1, verbose_name='gender')),
                ('birthday', models.DateField(default=datetime.date.today, help_text='format: 2020-05-01', verbose_name='date of birth')),
                ('contact_number', models.CharField(max_length=20, verbose_name='contact number')),
                ('address', models.TextField(verbose_name='address')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='grades.grade')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'student info',
                'verbose_name_plural': 'student info',
                'db_table': 'student',
            },
        ),
    ]
