# Generated by Django 5.1.2 on 2024-10-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_name', models.CharField(max_length=50, unique=True, verbose_name='class name')),
                ('grade_number', models.CharField(max_length=10, unique=True, verbose_name='class number')),
            ],
            options={
                'verbose_name': 'class',
                'verbose_name_plural': 'class name',
                'db_table': 'grade',
            },
        ),
    ]
