# Generated by Django 5.1.2 on 2024-11-18 22:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grades', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50, verbose_name='teacher name')),
                ('phone_number', models.CharField(max_length=10, unique=True, verbose_name='phone number')),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], max_length=1, verbose_name='gender')),
                ('birthday', models.DateField(help_text='format: 2020-05-01', verbose_name='birthday')),
                ('grade', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='grades.grade', verbose_name='manage class')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'teacher info',
                'verbose_name_plural': 'teacher info',
                'db_table': 'teacher',
            },
        ),
    ]
